//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "crate_keyword_to_crate")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub crate_fk: i64,
    pub keyword_fk: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::krate::Entity",
        from = "Column::CrateFk",
        to = "super::krate::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Krate,
    #[sea_orm(
        belongs_to = "super::crate_keyword::Entity",
        from = "Column::KeywordFk",
        to = "super::crate_keyword::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CrateKeyword,
}

impl Related<super::krate::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Krate.def()
    }
}

impl Related<super::crate_keyword::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrateKeyword.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
