//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "crate_author_to_crate")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub crate_fk: i64,
    pub author_fk: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::crate_author::Entity",
        from = "Column::AuthorFk",
        to = "super::crate_author::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CrateAuthor,
    #[sea_orm(
        belongs_to = "super::krate::Entity",
        from = "Column::CrateFk",
        to = "super::krate::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Krate,
}

impl Related<super::crate_author::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CrateAuthor.def()
    }
}

impl Related<super::krate::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Krate.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
