//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub mod prelude;

pub mod auth_token;
pub mod crate_author;
pub mod crate_author_to_crate;
pub mod crate_category;
pub mod crate_category_to_crate;
pub mod crate_group;
pub mod crate_index;
pub mod crate_keyword;
pub mod crate_keyword_to_crate;
pub mod crate_meta;
pub mod crate_user;
pub mod cratesio_crate;
pub mod cratesio_index;
pub mod cratesio_meta;
pub mod doc_queue;
pub mod group;
pub mod group_user;
pub mod krate;
pub mod owner;
pub mod session;
pub mod user;
